# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Instalar Python 3.11.3
        uses: actions/setup-python@v1
        with:
          python-version: 3.11.3
      - name: Instalar dependencias (pytest)
        run: |
          python -m pip install --upgrade pip
  # pip install -r requirements.txt
      - name: Ejecutar tests
        run: python -m test
